var DestinyTrialsDefinitions = {
  "145503874": {
    "activityHash": 145503874,
    "activityName": "Pantheon",
    "activityDescription": "Black Garden, Mars",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_pantheon.jpg",
    "rewards": [],
    "skulls": [],
    "heatmapImage": "/images/pantheon_heatmap.jpg",
    "headerImage": "/images/pantheon.jpg",
    "headerWideImage": "/images/pantheon_wide.jpg"
  },
  "257451727": {
    "activityHash": 257451727,
    "activityName": "Widow's Court",
    "activityDescription": "European Dead Zone, Earth",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/widows_court.jpg",
    "rewards": [],
    "skulls": []
  },
  "270739640": {
    "activityHash": 270739640,
    "activityName": "The Burning Shrine",
    "activityDescription": "Fields of Glass, Mercury",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_the_burning_shrine.jpg",
    "rewards": [],
    "skulls": []
  },
  "304857686": {
    "activityHash": 304857686,
    "activityName": "Asylum",
    "activityDescription": "Ishtar Sink, Venus",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_asylum.jpg",
    "rewards": [],
    "skulls": []
  },
  "419276631": {
    "activityHash": 419276631,
    "activityName": "Trials of Osiris",
    "activityDescription": "Only those who have proven their worth may enter the Trials.\n\nA string of victories will earn great rewards—but lose too many matches and your access will be denied.",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/common/destiny_content/icons/70a5300485b5af64a356bd6d5d7d608c.png",
    "releaseTime": 0,
    "activityLevel": 20,
    "completionFlagHash": 0,
    "activityPower": 8,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/placeholder.jpg",
    "rewards": [
      {
        "rewardItems": [
          {
            "itemHash": 538363648,
            "value": 0
          },
          {
            "itemHash": 1532971676,
            "value": 0
          },
          {
            "itemHash": 523605914,
            "value": 0
          }
        ]
      }
    ],
    "skulls": []
  },
  "506325623": {
    "activityHash": 506325623,
    "activityName": "The Anomaly",
    "activityDescription": "Mare Cognitum, Moon",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_the_anomaly.jpg",
    "rewards": [],
    "skulls": []
  },
  "532004957": {
    "activityHash": 532004957,
    "activityName": "Firebase Delphi",
    "activityDescription": "Eos Chasma, Mars",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_firebase_delphi.jpg",
    "rewards": [],
    "skulls": []
  },
  "715264086": {
    "activityHash": 715264086,
    "activityName": "Trials of Osiris",
    "activityDescription": "Only the worthy may face the Trials of Osiris, for only the worthy are strong enough to endure what is to come.\n\nA string of victories will earn great rewards - but lose too many matches, and you're out.",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 381621171,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/placeholder.jpg",
    "rewards": [
      {
        "rewardItems": [
          {
            "itemHash": 1600935051,
            "value": 0
          },
          {
            "itemHash": 1743040968,
            "value": 0
          }
        ]
      },
      {
        "rewardItems": [
          {
            "itemHash": 523605914,
            "value": 0
          }
        ]
      }
    ],
    "skulls": []
  },
  "715264087": {
    "activityHash": 715264087,
    "activityName": "Trials of Osiris",
    "activityDescription": "Only the worthy may face the Trials of Osiris, for only the worthy are strong enough to endure what is to come.\n\nA string of victories will earn great rewards - but lose three times and you're out.",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 1,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/placeholder.jpg",
    "rewards": [
      {
        "rewardItems": [
          {
            "itemHash": 523605914,
            "value": 0
          }
        ]
      },
      {
        "rewardItems": [
          {
            "itemHash": 1082476426,
            "value": 0
          },
          {
            "itemHash": 2873479814,
            "value": 0
          }
        ]
      }
    ],
    "skulls": []
  },
  "744855121": {
    "activityHash": 744855121,
    "activityName": "Thieves' Den",
    "activityDescription": "Ishtar Sink, Venus",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/thieves_den.jpg",
    "rewards": [],
    "skulls": []
  },
  "1272378257": {
    "activityHash": 1272378257,
    "activityName": "Shores of Time",
    "activityDescription": "Maat Mons, Venus",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_shores_of_time.jpg",
    "rewards": [],
    "skulls": []
  },
  "1596564652": {
    "activityHash": 1596564652,
    "activityName": "Black Shield",
    "activityDescription": "Firebase Thuria, Phobos",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/black_shield.jpg",
    "rewards": [],
    "skulls": []
  },
  "1868337040": {
    "activityHash": 1868337040,
    "activityName": "Twilight Gap",
    "activityDescription": "City Perimeter, Earth",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_twilight_gap_2.jpg",
    "rewards": [],
    "skulls": []
  },
  "2629315274": {
    "activityHash": 2629315274,
    "activityName": "Blind Watch",
    "activityDescription": "Meridian Bay, Mars",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_blind_watch.jpg",
    "rewards": [],
    "skulls": []
  },
  "3068511718": {
    "activityHash": 3068511718,
    "activityName": "The Cauldron",
    "activityDescription": "Ocean of Storms, Moon",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_cauldron.jpg",
    "rewards": [],
    "skulls": []
  },
  "3813402384": {
    "activityHash": 3813402384,
    "activityName": "Rusted Lands",
    "activityDescription": "Eastern Flood Zone, Earth",
    "icon": "/img/theme/destiny/icons/osiris_diamond.png",
    "releaseIcon": "/img/misc/missing_icon.png",
    "releaseTime": 0,
    "activityLevel": 0,
    "completionFlagHash": 0,
    "activityPower": 0,
    "minParty": 3,
    "maxParty": 3,
    "maxPlayers": 6,
    "destinationHash": 2777041980,
    "placeHash": 4088006058,
    "activityTypeHash": 736189348,
    "tier": -1,
    "pgcrImage": "/img/theme/destiny/bgs/pgcrs/crucible_the_rusted_lands.jpg",
    "rewards": [],
    "skulls": []
  }
};
