var DestinyTrialsDefinition = {
  145503874: {
    activityHash: 145503874,
    activityName: "Pantheon",
    activityDescription: "Black Garden, Mars",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_pantheon.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/pantheon.jpg",
    headerWideImage: "/images/pantheon_wide.jpg",
    heatmapImage: "/images/pantheon_heatmap.jpg"
  },
  257451727: {
    activityHash: 257451727,
    activityName: "Widow's Court",
    activityDescription: "European Dead Zone, Earth",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/widows_court.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/widows_court.jpg",
    headerWideImage: "/images/widows_court_wide.jpg",
    heatmapImage: "/images/widows_court_heatmap.jpg"
  },
  270739640: {
    activityHash: 270739640,
    activityName: "The Burning Shrine",
    activityDescription: "Fields of Glass, Mercury",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_the_burning_shrine.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/burning_shrine.jpg",
    headerWideImage: "/images/burning_shrine_wide.jpg",
    heatmapImage: "/images/burning_shrine_heatmap.jpg"
  },
  304857686: {
    activityHash: 304857686,
    activityName: "Asylum",
    activityDescription: "Ishtar Sink, Venus",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_asylum.jpg",
    rewards: [],
    skulls: []
  },
  506325623: {
    activityHash: 506325623,
    activityName: "The Anomaly",
    activityDescription: "Mare Cognitum, Moon",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_the_anomaly.jpg",
    rewards: [],
    skulls: []
  },
  532004957: {
    activityHash: 532004957,
    activityName: "Firebase Delphi",
    activityDescription: "Eos Chasma, Mars",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_firebase_delphi.jpg",
    rewards: [],
    skulls: []
  },
  744855121: {
    activityHash: 744855121,
    activityName: "Thieves' Den",
    activityDescription: "Ishtar Sink, Venus",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/thieves_den.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/thieves_den.jpg",
    headerWideImage: "/images/thieves_den_wide.jpg",
    heatmapImage: "/images/thieves_den_heatmap.jpg"
  },
  1272378257: {
    activityHash: 1272378257,
    activityName: "Shores of Time",
    activityDescription: "Maat Mons, Venus",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_shores_of_time.jpg",
    rewards: [],
    skulls: []
  },
  1596564652: {
    activityHash: 1596564652,
    activityName: "Black Shield",
    activityDescription: "Firebase Thuria, Phobos",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/black_shield.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/black_shield.jpg",
    headerWideImage: "/images/black_shield_wide.jpg",
    heatmapImage: "/images/black_shield_heatmap.jpg"
  },
  1868337040: {
    activityHash: 1868337040,
    activityName: "Twilight Gap",
    activityDescription: "City Perimeter, Earth",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_twilight_gap_2.jpg",
    rewards: [],
    skulls: []
  },
  2629315274: {
    activityHash: 2629315274,
    activityName: "Blind Watch",
    activityDescription: "Meridian Bay, Mars",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_blind_watch.jpg",
    rewards: [],
    skulls: []
  },
  3068511718: {
    activityHash: 3068511718,
    activityName: "The Cauldron",
    activityDescription: "Ocean of Storms, Moon",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_cauldron.jpg",
    rewards: [],
    skulls: [],
    headerImage: "/images/cauldron.jpg",
    headerWideImage: "/images/cauldron_wide.jpg",
    heatmapImage: "/images/cauldron_heatmap.jpg"
  },
  3813402384: {
    activityHash: 3813402384,
    activityName: "Rusted Lands",
    activityDescription: "Eastern Flood Zone, Earth",
    icon: "/img/theme/destiny/icons/osiris_diamond.png",
    releaseIcon: "/img/misc/missing_icon.png",
    releaseTime: 0,
    activityLevel: 0,
    completionFlagHash: 0,
    activityPower: 0,
    minParty: 3,
    maxParty: 3,
    maxPlayers: 6,
    destinationHash: 2777041980,
    placeHash: 4088006058,
    activityTypeHash: 736189348,
    tier: -1,
    pgcrImage: "/img/theme/destiny/bgs/pgcrs/crucible_the_rusted_lands.jpg",
    rewards: [],
    skulls: []
  }
};
