var DestinyHeavyWeaponDefinitions = {
  32959576: {
    hash: 32959576,
    name: 'The Dreammaker',
    description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
    icon: 'http://bungie.net/common/destiny_content/icons/08e1172583070119a8d4ac2528ad9232.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Rocket Launcher',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  32959577: {
    hash: 32959577,
      name: 'The Dreamwaker',
      description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
      icon: 'http://bungie.net/common/destiny_content/icons/a4987483ec02702da9193f1be404f7cc.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  46660196: {
    hash: 46660196,
      name: 'Admonisher III',
      description: 'Executor-issued rocket launcher for loyal supporters of the New Monarchy.',
      icon: 'http://bungie.net/common/destiny_content/icons/055175be7bcbce51e426a97ab7e6cd22.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  73994448: {
    hash: 73994448,
      name: 'Tomorrow\'s Answer',
      description: 'Could you please repeat the question?',
      icon: 'http://bungie.net/common/destiny_content/icons/be0d38e984fe3648fee6da817708916e.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Void Damage']
  },
  204520812: {
    hash: 204520812,
      name: 'Harbinger',
      description: 'A general-purpose Vanguard-issue rocket launcher. Apprentices at the GNT collaborative rebuild Barons into Harbingers.',
      icon: 'http://bungie.net/common/destiny_content/icons/4f97009023442404ae0fec9707c73cc8.jpg',
      tier: 'Uncommon',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  272343900: {
    hash: 272343900,
      name: 'Baron RS/2a',
      description: 'Shoulder-fired devastation. The Baron RS/2a is a general-purpose launcher that was used as a testbed for later development.',
      icon: 'http://bungie.net/common/destiny_content/icons/35b614cf6163658cc4890413fe84a1e0.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  517324839: {
    hash: 517324839,
      name: 'Admonisher III',
      description: 'Executor-issued high-impact weapon, for loyal supporters of the New Monarchy.',
      icon: 'http://bungie.net/common/destiny_content/icons/a2d2d879f09e414f3ef4ba82ea240e69.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  517625051: {
    hash: 517625051,
      name: 'Baron RS/1',
      description: 'Shoulder-fired devastation. The Baron is a general-purpose unguided explosive launcher.',
      icon: 'http://bungie.net/common/destiny_content/icons/4c70418f7576a7cd6b228cdb5cd263da.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  708578174: {
    hash: 708578174,
      name: 'Silvered Warmonger SA/4',
      description: 'A devastating Crux/Lomar launcher, earned through glory in the Crucible.',
      icon: 'http://bungie.net/common/destiny_content/icons/ca27bbbf00d125846dd56bf6e1d54c07.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  757040550: {
    hash: 757040550,
      name: 'Tomorrow\'s Answer',
      description: 'A prestigious trophy earned in battle during the Trials of Osiris.',
      icon: 'http://bungie.net/common/destiny_content/icons/cef67afa7b6478006898e621aa5513ae.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Void Damage']
  },
  805224273: {
    hash: 805224273,
      name: 'Radegast\'s Fury',
      description: 'A rocket launcher forged in fire by the Lords of the Iron Banner.',
      icon: 'http://bungie.net/common/destiny_content/icons/5240b6f846c833991d35ff72ce9a8f14.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  855740583: {
    hash: 855740583,
      name: 'Baron RS/2',
      description: 'Shoulder-fired devastation. The Baron is a general-purpose launcher; this one bears the inscription \'FULL STOP\' on the trigger guard.',
      icon: 'http://bungie.net/common/destiny_content/icons/11a193bbf068521b5eb5548c7d167789.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  906167852: {
    hash: 906167852,
      name: 'Exodus Plan RS/1',
      description: 'A high-impact weapon, modified by Dead Orbit\'s superb technicians and specialists.',
      icon: 'http://bungie.net/common/destiny_content/icons/35a6cb52df74c77392e1fa67b9ad65b7.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  926066377: {
    hash: 926066377,
      name: 'Tomorrow\'s Answer',
      description: 'A prestigious trophy earned in battle during the Trials of Osiris.',
      icon: 'http://bungie.net/common/destiny_content/icons/cef67afa7b6478006898e621aa5513ae.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Void Damage']
  },
  996787434: {
    hash: 996787434,
      name: 'Radegast\'s Fury',
      description: 'A rocket launcher forged in fire by the Lords of the Iron Banner.',
      icon: 'http://bungie.net/common/destiny_content/icons/08e1172583070119a8d4ac2528ad9232.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1163110499: {
    hash: 1163110499,
      name: 'The Dreamwaker',
      description: 'The design for this powerful weapon came to Techeun Shuro in a dream.',
      icon: 'http://bungie.net/common/destiny_content/icons/5feaa23564a63e893b8e7f2c7660b92e.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1254347838: {
    hash: 1254347838,
      name: 'One Way Ticket 000',
      description: 'A vacation at the ol\' triple zero.',
      icon: 'http://bungie.net/common/destiny_content/icons/44096c726370de419a1fabce49d2ea0d.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1274330686: {
    hash: 1274330686,
      name: 'Truth',
      description: '“...is where you seek it.“ – Lomar',
      icon: 'http://bungie.net/common/destiny_content/icons/66940c4cd6d88252466157a630a0c3fa.jpg',
      tier: 'Exotic',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Void Damage']
  },
  1274330687: {
    hash: 1274330687,
      name: 'Gjallarhorn',
      description: '\'If there is beauty in destruction, why not also in its delivery?\' - Feizel Crux',
      icon: 'http://bungie.net/common/destiny_content/icons/eb8377390504838c0190d8d56e70d28e.jpg',
      tier: 'Exotic',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Solar Damage']
  },
  1415224434: {
    hash: 1415224434,
      name: 'Exodus Plan RS/1',
      description: 'A rocket launcher modified by Dead Orbit\'s superb technicians and specialists.',
      icon: 'http://bungie.net/common/destiny_content/icons/7ef5eca147fa8da8f97d470b5992863b.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1460033860: {
    hash: 1460033860,
      name: 'The Cure',
      description: 'A rocket launcher named and sanctified by the leaders of the Future War Cult.',
      icon: 'http://bungie.net/common/destiny_content/icons/ee424fada73f3ddd751a05d531b66be6.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1517489904: {
    hash: 1517489904,
      name: 'Lacerta',
      description: 'A Guardian relic named for the lizard of the night sky.',
      icon: 'http://bungie.net/common/destiny_content/icons/9f32d843601efcf163f84e150cffaa11.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1610212078: {
    hash: 1610212078,
      name: 'Steel Oracle Z-11',
      description: '\'I foresee fire. Fire and screams.\' \'You would, mate. You\'re a rocket launcher.\'',
      icon: 'http://bungie.net/common/destiny_content/icons/c8f0773d87d960312e56c81271a7f865.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1742815376: {
    hash: 1742815376,
      name: 'Affentheater C/L-A',
      description: 'Our enemies watch us huddle and just laugh. But it\'s our show now.',
      icon: 'http://bungie.net/common/destiny_content/icons/74896f9e43b1974132b558c087e0be50.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1742815377: {
    hash: 1742815377,
      name: 'Whisper C/L-A',
      description: 'This portable cataclysm bears its name with a certain irony.',
      icon: 'http://bungie.net/common/destiny_content/icons/00cf00f99b73e2b7ca30f07ee8b63e55.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1742815378: {
    hash: 1742815378,
      name: 'Disruptor 5000',
      description: 'A general-purpose launcher built on the skeleton of a recovered Golden Age design.',
      icon: 'http://bungie.net/common/destiny_content/icons/f7a4d93b51990d15c7988df4083235c7.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1742815379: {
    hash: 1742815379,
      name: 'Happy Boomer',
      description: 'You just gotta do what you love.',
      icon: 'http://bungie.net/common/destiny_content/icons/a75041dcbed4b03ab74e2ef573a6efdd.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1880992098: {
    hash: 1880992098,
      name: 'Painted Camelot SA/4',
      description: 'A hard-hitting Crux/Lomar rocket launcher, earned through glory in the Crucible.',
      icon: 'http://bungie.net/common/destiny_content/icons/e9cf2e4444370ceaab42a4ef1010b9b3.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  1880992099: {
    hash: 1880992099,
      name: 'Primed Khan RS/4',
      description: 'A hard-hitting Crux/Lomar rocket launcher, earned through glory in the Crucible.',
      icon: 'http://bungie.net/common/destiny_content/icons/79b6858c528bccb63d311c6080c2cf2f.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552008: {
    hash: 2101552008,
      name: 'Despot SA/5',
      description: 'A high-end general-purpose launcher, built for oppression through controlled devastation.',
      icon: 'http://bungie.net/common/destiny_content/icons/4c2e680a593be22731f53f71dc66ad03.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552009: {
    hash: 2101552009,
      name: 'Sultan SA/5',
      description: 'Roaring devastation in a sophisticated can.',
      icon: 'http://bungie.net/common/destiny_content/icons/4225c17e6d732df73b6987b617bddca2.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552010: {
    hash: 2101552010,
      name: 'Chamberlain SA/5',
      description: 'A high-end general-purpose launcher, built for Guardians to re-rig in the field.',
      icon: 'http://bungie.net/common/destiny_content/icons/746ef934aa43c050fe63937102ffbc90.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552011: {
    hash: 2101552011,
      name: 'Herald SA/5',
      description: 'Announce the coming of the Light with a steady roar.',
      icon: 'http://bungie.net/common/destiny_content/icons/e23ae796ba8249bdb729c1362f6bd089.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552012: {
    hash: 2101552012,
      name: 'Bishop RS/5',
      description: 'The study of Golden Age relics has given birth to fearsome, adaptable weapons.',
      icon: 'http://bungie.net/common/destiny_content/icons/ea7b14c18d14cb1fa801fdd6ff8dd43d.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552013: {
    hash: 2101552013,
      name: 'Duchess RS/5',
      description: 'Bristling with sophisticated tactical systems, the RS/5 dictates the shape of the battle.',
      icon: 'http://bungie.net/common/destiny_content/icons/2a72b0c69460635446268c1cd1c0b675.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2101552015: {
    hash: 2101552015,
      name: 'Overlord SA/5',
      description: 'For those who seek the ruin of their enemies, the SA/5 variant Overlord is the answer.',
      icon: 'http://bungie.net/common/destiny_content/icons/d357850ccc8618298653fe74cc2080fb.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2361858758: {
    hash: 2361858758,
      name: 'Hunger of Crota',
      description: 'Would you defy Me? I am the eater of hope.',
      icon: 'http://bungie.net/common/destiny_content/icons/9968974f2c73c2757277d5ac71907d91.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Solar Damage']
  },
  2437702841: {
    hash: 2437702841,
      name: 'Unfriendly Giant',
      description: 'Unfriendly is really too harsh. He\'s just a bit shy.',
      icon: 'http://bungie.net/common/destiny_content/icons/449e4ca21acdb67a72d3052f9dddc08e.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2726256225: {
    hash: 2726256225,
      name: 'Admonisher III',
      description: 'Executor-issued rocket launcher for loyal supporters of the New Monarchy.',
      icon: 'http://bungie.net/common/destiny_content/icons/055175be7bcbce51e426a97ab7e6cd22.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2764161076: {
    hash: 2764161076,
      name: 'Butcher SA/3',
      description: 'Heavy damage. To the point. Caution is advised. Enjoy.',
      icon: 'http://bungie.net/common/destiny_content/icons/fdff030883aaba9dc37ab7572d0fa05a.jpg',
      tier: 'Uncommon',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2764161077: {
    hash: 2764161077,
      name: 'Breaker SA/3',
      description: 'The SA/3 Breaker answers a requirement for a hard-hitting launcher to defeat new varieties of Fallen armor.',
      icon: 'http://bungie.net/common/destiny_content/icons/f300ef5f47beabf1127387a5905cc53f.jpg',
      tier: 'Uncommon',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2764161078: {
    hash: 2764161078,
      name: 'Jester SA/3',
      description: 'The SA/3 Jester maintains the Jester series\' focus on precise delivery, but with expanded capability.',
      icon: 'http://bungie.net/common/destiny_content/icons/19a25ad30229431f170f316c1c416f03.jpg',
      tier: 'Uncommon',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  2764161079: {
    hash: 2764161079,
      name: 'Deacon RS/3',
      description: 'The RS/3 Deacon is a tactical upgrade to the flexible Deacon series.',
      icon: 'http://bungie.net/common/destiny_content/icons/328132a7e869b71dae0424043ac14fa6.jpg',
      tier: 'Uncommon',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3104387070: {
    hash: 3104387070,
      name: 'The Dreamwaker',
      description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
      icon: 'http://bungie.net/common/destiny_content/icons/a4987483ec02702da9193f1be404f7cc.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3153232297: {
    hash: 3153232297,
      name: 'Valedictorian 9-44',
      description: 'Send that one to the front of the class!',
      icon: 'http://bungie.net/common/destiny_content/icons/74f1d0df8d5aba2f95140c13650970af.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3167958228: {
    hash: 3167958228,
      name: 'Deacon RS/2',
      description: 'Shoulder-mounted devastation. A general-purpose launcher, the Deacon was designed to kill Fallen and their Walkers.',
      icon: 'http://bungie.net/common/destiny_content/icons/814d768c8f43ed0d98ce402fa8031b9b.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  3167958229: {
    hash: 3167958229,
      name: 'Jester SA/2',
      description: 'Shoulder-mounted devastation. The Jester takes its job very seriously - it\'s designed to put munitions dead on target.',
      icon: 'http://bungie.net/common/destiny_content/icons/cd792620143137486ebfb88929351fe5.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  3167958230: {
    hash: 3167958230,
      name: 'Breaker SA/2',
      description: 'Shoulder-mounted devastation. Like its cousin the Butcher, the Breaker puts raw damage first.',
      icon: 'http://bungie.net/common/destiny_content/icons/9e1a300f3ed0fb087629abe7212b0589.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  3167958231: {
    hash: 3167958231,
      name: 'Butcher SA/2',
      description: 'Shoulder-mounted devastation. The Butcher\'s heavy payload delivers catastrophic damage.',
      icon: 'http://bungie.net/common/destiny_content/icons/9e1a300f3ed0fb087629abe7212b0589.jpg',
      tier: 'Common',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Kinetic Damage']
  },
  3420129286: {
    hash: 3420129286,
      name: 'The Fear',
      description: 'A high-impact weapon, augmented, named and sanctified by the leaders of the Future War Cult.',
      icon: 'http://bungie.net/common/destiny_content/icons/4892d7a5094686522a0794f54c7f46ca.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3705198528: {
    hash: 3705198528,
      name: 'Dragon\'s Breath',
      description: 'Burn the world. Burn it all.',
      icon: 'http://bungie.net/common/destiny_content/icons/8df2a0fe0c782cc48951c0939f390cfc.jpg',
      tier: 'Exotic',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Solar Damage']
  },
  3747674784: {
    hash: 3747674784,
      name: 'The Good Doctor',
      description: 'Let\'s make a house call.',
      icon: 'http://bungie.net/common/destiny_content/icons/6ae80814050146ee65cc05685b3211a3.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3747674785: {
    hash: 3747674785,
      name: 'Big Rig XXL',
      description: 'This is my truck.',
      icon: 'http://bungie.net/common/destiny_content/icons/fa8c705d987bc22a30d05e5e2921ff4a.jpg',
      tier: 'Rare',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3772051159: {
    hash: 3772051159,
      name: 'The Last Rebellion',
      description: 'Insurrection will not be tolerated.',
      icon: 'http://bungie.net/common/destiny_content/icons/c4baaf3ff93212a71919c82c93663a31.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Void Damage']
  },
  3807770941: {
    hash: 3807770941,
      name: 'Hezen Vengeance',
      description: 'The Hezen Axis Mind is tireless and infinite. While it cannot be stopped... it can be paused.',
      icon: 'http://bungie.net/common/destiny_content/icons/ed2b5218ca7a359f7917ed82a9b3288b.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: [],
      damageType: ['Solar Damage']
  },
  3881784492: {
    hash: 3881784492,
      name: 'Pax Totalus EPR8',
      description: 'Better living through focused fire.',
      icon: 'http://bungie.net/common/destiny_content/icons/1b8d3b63570356b0279ea8d8fa38f449.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  3947396344: {
    hash: 3947396344,
      name: 'Radegast\'s Fury',
      description: 'A high-impact weapon, forged in fire by the Lords of the Iron Banner.',
      icon: 'http://bungie.net/common/destiny_content/icons/6348db0ede20f0362db92f661fcf7822.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  4086430879: {
    hash: 4086430879,
      name: 'The Cure',
      description: 'A rocket launcher named and sanctified by the leaders of the Future War Cult.',
      icon: 'http://bungie.net/common/destiny_content/icons/4cc6e9c4d05a9126d372e8ac6a313846.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  4233409820: {
    hash: 4233409820,
      name: 'Uppercut Payload',
      description: 'Knee shaker/Nose breaker.',
      icon: 'http://bungie.net/common/destiny_content/icons/a79d26eb4ca512e385fc42d65dca3efe.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  4233409821: {
    hash: 4233409821,
      name: 'Wastelander V2V',
      description: 'Nothing good can come of this.',
      icon: 'http://bungie.net/common/destiny_content/icons/3882ff8584a4bac08c87c9b4c958fd8e.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  4233409823: {
    hash: 4233409823,
      name: 'The Ash Factory',
      description: 'Blot out the sun.',
      icon: 'http://bungie.net/common/destiny_content/icons/c238e034d0d5002f2f90ac6743c709bb.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  4251892203: {
    hash: 4251892203,
      name: 'Exodus Plan RS/1',
      description: 'A rocket launcher modified by Dead Orbit\'s superb technicians and specialists.',
      icon: 'http://bungie.net/common/destiny_content/icons/7ef5eca147fa8da8f97d470b5992863b.jpg',
      tier: 'Legendary',
      type: 'Weapon',
      subType: 'Rocket Launcher',
      bucket: 'BUCKET_HEAVY_WEAPON',
      damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
      damageType: []
  },
  23851077: {
    hash: 23851077,
    name: 'The Infinite Theorem',
    description: 'A prestigious trophy earned in battle during the Trials of Osiris.',
    icon: 'http://bungie.net/common/destiny_content/icons/c9577d94e13b0c1a9b9fba99738b576e.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  136148814: {
    hash: 136148814,
    name: 'Jolder\'s Hammer',
    description: 'A heavy-fire weapon, forged in fire by the Lords of the Iron Banner.',
    icon: 'http://bungie.net/common/destiny_content/icons/dde1039d10252fd494b8aba9cc400c26.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  152628833: {
    hash: 152628833,
    name: 'Corrective Measure',
    description: 'It breaks the rules of reality as ruthlessly as it shatters your foes.',
    icon: 'http://bungie.net/common/destiny_content/icons/34d5d4f4286c7b4e4ef66f39c10f0238.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Void Damage']
  },
  327458264: {
    hash: 327458264,
    name: 'Darius-B',
    description: 'Fully automatic heavy machine gun. The Darius Bravo slams targets with massive slugs, putting damage above all else.',
    icon: 'http://bungie.net/common/destiny_content/icons/dca8d193dd52541cbec73e9af10d0b7f.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  327458265: {
    hash: 327458265,
    name: 'Sargon-B2',
    description: 'Fully automatic heavy machine gun. The Sargon-B2 is a general-purpose weapon noted for its pleasant ergonomics.',
    icon: 'http://bungie.net/common/destiny_content/icons/7471c7980716adda55d027e70a43c6f1.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  327458266: {
    hash: 327458266,
    name: 'Cyrus-B',
    description: 'Fully automatic heavy machine gun. The Cyrus Bravo slams targets with massive slugs, putting damage above all else.',
    icon: 'http://bungie.net/common/destiny_content/icons/383d0fc3fc5574687fdf438027ff52a9.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  327458267: {
    hash: 327458267,
    name: 'Tamerlane-B',
    description: 'Fully automatic heavy machine gun. The Tamerlane Bravo is a long-range support weapon with excellent precision for its class.',
    icon: 'http://bungie.net/common/destiny_content/icons/370c220827646e97c338d86e5aaff794.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  422175840: {
    hash: 422175840,
    name: 'Zombie Apocalypse WF47',
    description: 'Ready for one breed of armageddon.',
    icon: 'http://bungie.net/common/destiny_content/icons/cd4d4f4576f7fb3976c4e8a9a726829b.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  639554740: {
    hash: 639554740,
    name: 'Wolves\' Curse',
    description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
    icon: 'http://bungie.net/common/destiny_content/icons/d19174f03c3e8be9144ad0da74870685.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  639554741: {
    hash: 639554741,
    name: 'Wolves\' Bane',
    description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
    icon: 'http://bungie.net/common/destiny_content/icons/47fdfcc869011e76c386afc75f577ca6.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  687225130: {
    hash: 687225130,
    name: 'Sargon-B1',
    description: 'Fully automatic heavy machine gun. The Sargon-B1 Team Support Weapon is an answer to Fallen shock tactics.',
    icon: 'http://bungie.net/common/destiny_content/icons/9d8075902eb094c9a353195ff2702c18.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  753391730: {
    hash: 753391730,
    name: 'The Culling',
    description: 'A machine gun named and sanctified by the leaders of the Future War Cult.',
    icon: 'http://bungie.net/common/destiny_content/icons/0d5b811bba433e9baa58499f30faf8f0.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  788203480: {
    hash: 788203480,
    name: 'Song of Ir Yût',
    description: 'It is the song of endings.',
    icon: 'http://bungie.net/common/destiny_content/icons/2257393aeb4df5da344b02f4107473cc.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Arc Damage']
  },
  823763462: {
    hash: 823763462,
    name: 'Horologium',
    description: 'A Guardian relic named for the clock of the night sky.',
    icon: 'http://bungie.net/common/destiny_content/icons/9ead181ee4827938f67521aee7b03810.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  843443257: {
    hash: 843443257,
    name: '###Missing String: lc en index 310 hash 1797611478 name machinegun0###',
    description: '###Missing String: lc en index 310 hash 2816620937 name machinegun0_description###',
    icon: 'http://bungie.net/common/destiny_content/icons/7980708e0ccd17ac66eabe13a821d60d.jpg',
    tier: 'Exotic',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Void Damage']
  },
  910389904: {
    hash: 910389904,
    name: 'Wolves\' Bane',
    description: 'An Awoken gift from the Reef, marked with the Queen\'s crown.',
    icon: 'http://bungie.net/common/destiny_content/icons/47fdfcc869011e76c386afc75f577ca6.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1055280512: {
    hash: 1055280512,
    name: 'Unending Deluge III',
    description: 'When it rains…',
    icon: 'http://bungie.net/common/destiny_content/icons/e89c99abbe918c4b7777e5330ec46f04.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1055280513: {
    hash: 1055280513,
    name: 'BTRD-345',
    description: 'Better than the rest.',
    icon: 'http://bungie.net/common/destiny_content/icons/324bca7a38447bdc88a8a36f9a41dd3f.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1055280515: {
    hash: 1055280515,
    name: 'Backscratcher 9.0',
    description: 'Feels so good. For you, not them.',
    icon: 'http://bungie.net/common/destiny_content/icons/72848696a3c2476badecc4aee994dfb0.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1130638095: {
    hash: 1130638095,
    name: 'Sargon-B',
    description: 'Fully automatic heavy machine gun. The Sargon B-series delivers an improved fluorocarbon cooling system.',
    icon: 'http://bungie.net/common/destiny_content/icons/e71936e94aca9645706f016b92a87d8e.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  1204023325: {
    hash: 1204023325,
    name: 'Prestige IV',
    description: 'Executor-issued machine gun for loyal supporters of the New Monarchy.',
    icon: 'http://bungie.net/common/destiny_content/icons/d776c56ccb92b08e4bc3bc7ef5909df2.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1375158428: {
    hash: 1375158428,
    name: 'Deviant Gravity-A',
    description: 'A machine gun modified by Dead Orbit\'s superb technicians and specialists.',
    icon: 'http://bungie.net/common/destiny_content/icons/1bdc021c53a7eb8109d1efbf0b2dca18.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1382627864: {
    hash: 1382627864,
    name: 'The Culling',
    description: 'A heavy fire weapon, named and sanctified by the leaders of the Future War Cult.',
    icon: 'http://bungie.net/common/destiny_content/icons/549a877e667cfab16e70121d9389807b.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1409833631: {
    hash: 1409833631,
    name: 'Chain of Orbiks-Fel',
    description: 'The destruction of the Wolfship Orbiks-Fel during the Reef Wars is commemorated with every round fired.',
    icon: 'http://bungie.net/common/destiny_content/icons/0d34dbe0d595df8dc261ac48b09a4e8e.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Void Damage']
  },
  1857133658: {
    hash: 1857133658,
    name: 'BTRD-345',
    description: 'A multirole Vanguard machine gun. The serial number memorializes the number of kills the prototype scored in field test.',
    icon: 'http://bungie.net/common/destiny_content/icons/42020949a4a4507e620049b0b26ed9ae.jpg',
    tier: 'Uncommon',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  1883086571: {
    hash: 1883086571,
    name: 'Deviant Gravity-A',
    description: 'A machine gun modified by Dead Orbit\'s superb technicians and specialists.',
    icon: 'http://bungie.net/common/destiny_content/icons/1bdc021c53a7eb8109d1efbf0b2dca18.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1903292368: {
    hash: 1903292368,
    name: 'MG18A Harm\'s Way',
    description: 'The nothingness dispenser.',
    icon: 'http://bungie.net/common/destiny_content/icons/e4babb644dc0d8d5b237df6f5bdde051.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  1990440986: {
    hash: 1990440986,
    name: 'Arma Engine DOA',
    description: 'Heavy firepower modified to fit the exacting specifications of Dead Orbit\'s expanding arsenal.',
    icon: 'http://bungie.net/common/destiny_content/icons/0683ac914c8714f66eec04be40adb78f.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2352707666: {
    hash: 2352707666,
    name: 'Prestige IV',
    description: 'Executor-issued machine gun for loyal supporters of the New Monarchy.',
    icon: 'http://bungie.net/common/destiny_content/icons/d776c56ccb92b08e4bc3bc7ef5909df2.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248000: {
    hash: 2569248e3,
    name: 'Xerxes-E1',
    description: 'Echo-1 variant of the popular Xerxes. The weapon\'s corkscrew heart pumps coolant blood.',
    icon: 'http://bungie.net/common/destiny_content/icons/7de68f2d2b4524ecba4b32cc6ce715b2.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248001: {
    hash: 2569248001,
    name: 'Xerxes-E',
    description: 'Beneath the loud color scheme is an intricate mechanism utterly devoted to the delivery of brute force.',
    icon: 'http://bungie.net/common/destiny_content/icons/b8862066de1244ad7482c78a2bca1a13.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248003: {
    hash: 2569248003,
    name: 'Genghis-E1',
    description: 'Echo-1 Genghis variant, built to put rounds through Cabal armor and anything inside.',
    icon: 'http://bungie.net/common/destiny_content/icons/9ecf41d56143b2a0a985a21511b91b9f.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248004: {
    hash: 2569248004,
    name: 'Hannibal-E',
    description: 'This Echo variant is rigged for destruction through the delivery of sustained heavy fire.',
    icon: 'http://bungie.net/common/destiny_content/icons/efabdce73543d087571bea8d8f1a9b70.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248005: {
    hash: 2569248005,
    name: 'Genghis-E',
    description: 'The heavy Genghis Delta machine gun uses sapphire wiring to integrate tactical systems.',
    icon: 'http://bungie.net/common/destiny_content/icons/8c99318f61d50a91095c6a801faf4a3e.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248006: {
    hash: 2569248006,
    name: 'Red River Mk. 40',
    description: 'It\'ll live up to its name, just as long as the target actually bleeds something red.',
    icon: 'http://bungie.net/common/destiny_content/icons/12dbb3abd079d6dd502d0e29b629e7be.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2569248007: {
    hash: 2569248007,
    name: 'Tamerlane-E1',
    description: 'The heavy Echo-1 Tamerlane uses sapphire wiring to integrate tactical systems.',
    icon: 'http://bungie.net/common/destiny_content/icons/193c2fa45317637d56e72bf1829d25fe.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2670848871: {
    hash: 2670848871,
    name: 'The Culling',
    description: 'A machine gun named and sanctified by the leaders of the Future War Cult.',
    icon: 'http://bungie.net/common/destiny_content/icons/187661da2478ca877b5f990fa4641df6.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  2840351675: {
    hash: 2840351675,
    name: 'Sargon-A',
    description: 'Fully automatic heavy machine gun. The Sargon-A Team Support Weapon is an all-purpose death machine.',
    icon: 'http://bungie.net/common/destiny_content/icons/7471c7980716adda55d027e70a43c6f1.jpg',
    tier: 'Common',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  2853794413: {
    hash: 2853794413,
    name: 'Jolder\'s Hammer',
    description: 'A machine gun forged in fire by the Lords of the Iron Banner.',
    icon: 'http://bungie.net/common/destiny_content/icons/d79747cb8c40b21b7ee2fe1e7b0f362f.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3028978726: {
    hash: 3028978726,
    name: 'The Infinite Theorem',
    description: 'In the mirrorlike crags of the Fields of Glass, a single mote of dust produces infinite reflections.',
    icon: 'http://bungie.net/common/destiny_content/icons/80f7fd21d4ef593326fdb2442cbbdf7e.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Arc Damage']
  },
  3096129877: {
    hash: 3096129877,
    name: 'THE SWARM',
    description: 'Hunger is the all of it, and it is all of hunger.',
    icon: 'http://bungie.net/common/destiny_content/icons/35c98dcf01f94b0d6bd1453c9b571076.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3191797830: {
    hash: 3191797830,
    name: 'Super Good Advice',
    description: 'This weapon is full of it.',
    icon: 'http://bungie.net/common/destiny_content/icons/241f4ca98645b111fd39902ef7338009.jpg',
    tier: 'Exotic',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Solar Damage']
  },
  3191797831: {
    hash: 3191797831,
    name: 'Thunderlord',
    description: '\'They rest quiet on fields afar…for this is no ending, but the eye.\'',
    icon: 'http://bungie.net/common/destiny_content/icons/8fdb2b8a1b871a01bc09452c4192771a.jpg',
    tier: 'Exotic',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Arc Damage']
  },
  3244859508: {
    hash: 3244859508,
    name: 'Jolder\'s Hammer',
    description: 'A machine gun forged in fire by the Lords of the Iron Banner.',
    icon: 'http://bungie.net/common/destiny_content/icons/1f05035331db89a31441c2e30f1f0b86.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3458668152: {
    hash: 3458668152,
    name: 'The Infinite Theorem',
    description: 'A prestigious trophy earned in battle during the Trials of Osiris.',
    icon: 'http://bungie.net/common/destiny_content/icons/c9577d94e13b0c1a9b9fba99738b576e.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: [],
    damageType: ['Kinetic Damage']
  },
  3486170339: {
    hash: 3486170339,
    name: 'Painted Artemisia-D',
    description: 'A highly accurate Häkke heavy machine gun, earned through glory in the Crucible.',
    icon: 'http://bungie.net/common/destiny_content/icons/1d3a4cfb622b49c60e3d5572728e6e77.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3516613398: {
    hash: 3516613398,
    name: 'Arighan\'s Blossom',
    description: 'Built in tribute to a legend.',
    icon: 'http://bungie.net/common/destiny_content/icons/147cf7f8bc2ff10534e6c24a2267634d.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3841705359: {
    hash: 3841705359,
    name: 'Pacifier X',
    description: 'Executor-issued heavy-fire weapon, custom-rigged for loyal supporters of the New Monarchy.',
    icon: 'http://bungie.net/common/destiny_content/icons/a6d3153546ecf12d02b4a1a6aee254f6.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3863146768: {
    hash: 3863146768,
    name: 'Bronzed Thutmose-D',
    description: 'A powerful Häkke firearm, earned through glory in the Crucible.',
    icon: 'http://bungie.net/common/destiny_content/icons/7219f245aa7654d4667eccde2d24e8c3.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  3878440319: {
    hash: 3878440319,
    name: 'Sawtooth Oscillator',
    description: 'Additive synthesis, where A is amplitude and B is bullets in their face.',
    icon: 'http://bungie.net/common/destiny_content/icons/42fefb860351cd5c1a98c20990b260c0.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4026257891: {
    hash: 4026257891,
    name: 'Wolves\' Bane',
    description: 'During the Hildian Campaign, the Queen had need of weapons that could fire in a vacuum as well as an atmosphere.',
    icon: 'http://bungie.net/common/destiny_content/icons/887bdbd88a396f5eb4ebebbc1bc2c956.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4091910568: {
    hash: 4091910568,
    name: 'Sargon-C',
    description: 'Sargon Charlie is a precision support weapon. A smart-gel barrel bath sinks heat and keeps shot grouping tight.',
    icon: 'http://bungie.net/common/destiny_content/icons/fcc11fb84ef3e44a6067e342de935b10.jpg',
    tier: 'Uncommon',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4091910569: {
    hash: 4091910569,
    name: 'Darius-C',
    description: 'This high-powered machine gun delivers inertia-coupled ram rounds, inflicting extraordinary damage.',
    icon: 'http://bungie.net/common/destiny_content/icons/7f058a604853d13cfd9abba129c835db.jpg',
    tier: 'Uncommon',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4091910570: {
    hash: 4091910570,
    name: 'Tamerlane-C3',
    description: 'The Tamerlane-C3 team support gun boasts a mag-suspended precision barrel and onboard electronics.',
    icon: 'http://bungie.net/common/destiny_content/icons/c3f3dd352306c33933b55c7f6126b05b.jpg',
    tier: 'Uncommon',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4091910571: {
    hash: 4091910571,
    name: 'Xerxes-C',
    description: 'Conquer new worlds with the decisive thunderclap of the Xerxes\' heavy rounds.',
    icon: 'http://bungie.net/common/destiny_content/icons/5fff874c423ec9b356e128f71db604c1.jpg',
    tier: 'Uncommon',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Kinetic Damage', 'Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4151458533: {
    hash: 4151458533,
    name: 'Against All Odds',
    description: 'Threat assessment calculates your odds of survival at 3,721:1...unless you pull this trigger.',
    icon: 'http://bungie.net/common/destiny_content/icons/e367d3425d05bdb3c0de481bb8199bd7.jpg',
    tier: 'Legendary',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4155670896: {
    hash: 4155670896,
    name: 'Formerly Penitent',
    description: 'Belt-fed absolution.',
    icon: 'http://bungie.net/common/destiny_content/icons/3d4c7dfdfeae6c086e48e9ac92fe3b8e.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4155670897: {
    hash: 4155670897,
    name: 'SudaZomba-3',
    description: 'Sing along. The rhythm\'s not hard to catch.',
    icon: 'http://bungie.net/common/destiny_content/icons/9a30c15d123a386e447b42bf39c2c6f9.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4155670898: {
    hash: 4155670898,
    name: 'BFF 2.0',
    description: 'Sometimes, no matter how much it hurts, you just can\'t pass up a chance to upgrade.',
    icon: 'http://bungie.net/common/destiny_content/icons/8bae13997bd561a4672b81fcc155b936.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  },
  4155670899: {
    hash: 4155670899,
    name: 'Spirit of Alliance',
    description: 'Named by a very optimistic Earthborn Awoken, or his equally oblivious Reefborn counterpart.',
    icon: 'http://bungie.net/common/destiny_content/icons/d3cc94d4da9bfa11e8c693b13eb04594.jpg',
    tier: 'Rare',
    type: 'Weapon',
    subType: 'Machine Gun',
    bucket: 'BUCKET_HEAVY_WEAPON',
    damageTypeRolls: ['Void Damage', 'Solar Damage', 'Arc Damage'],
    damageType: []
  }
};
